# Generated by Django 3.0 on 2025-03-04 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_groupchat'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('MENTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Mentor')),
            ],
        ),
    ]
